[package]
name = "hyper-mysql"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["mysql", "runtime-tokio-native-tls"] }
root@0dfe30f3c5fc:/home/rust/hyper-mysql#

